-- -- detect if we are running inside nixos
-- if true  then
--   -- if so, nixos will handle the installation of lsp servers
--   return {
--     "neovim/nvim-lspconfig",
--     dependencies = {
--       'Hoffs/omnisharp-extended-lsp.nvim',
--     },
--     config = function()
--       require('lsp').setup()
--     end
--   }
-- end
--
--
--
--
-- return {
--   "williamboman/mason.nvim",
--   dependencies = {
--     'williamboman/mason-lspconfig.nvim',
--     'neovim/nvim-lspconfig',
--     'Hoffs/omnisharp-extended-lsp.nvim',
--   },
--   config = function()
--     local lspconfig = require("lspconfig")
--     -- lspconfig.setup({
--     --   opts = {
--     --     autoformat = false,
--     --   },
--     -- })
--     require("mason").setup()
--     local function getInstallPath(package)
--       local registry = require("mason-registry")
--       return registry.get_package(package):get_install_path()
--     end
--
--     local capabilities = vim.lsp.protocol.make_client_capabilities()
--     capabilities.textDocument.foldingRange = {
--       dynamicRegistration = false,
--       lineFoldingOnly = true
--     }
--     require("mason-lspconfig").setup({
--       ensure_installed = {},
--       automatic_installation = {},
--       handlers = {
--         -- handles jsonls rust_analyzer gopls
--         function(server_name) -- default handler
--           lspconfig[server_name].setup {
--             capabilities = capabilities,
--           }
--         end,
--
--         lua_ls = function()
--           lspconfig.lua_ls.setup {
--             capabilities = capabilities,
--             settings = {
--               Lua = {
--                 runtime = { version = 'LuaJIT', },
--                 diagnostics = {
--                   -- Get the language server to recognize the `vim` global
--                   globals = { 'vim' },
--                 },
--                 workspace = {
--                   -- Make the server aware of Neovim runtime files
--                   library = vim.api.nvim_get_runtime_file("", true),
--                   checkThirdParty = false,
--                 },
--               },
--             },
--           }
--         end,
--
--         volar = function()
--           lspconfig.volar.setup {
--             filetypes = {
--               'typescript',
--               'javascript',
--               'javascriptreact',
--               'typescriptreact',
--               'vue',
--               'html',
--               'json'
--             },
--             --[[ on_attach = on_attach({
--               -- TODO Still not too happy with this
--               customFormatter = function()
--                 vim.cmd "EslintFixAll"
--               end
--             }), ]]
--           }
--         end,
--
--         eslint = function()
--           lspconfig.eslint.setup {
--             filetypes = {
--               'typescript',
--               'javascript',
--               'vue',
--             },
--             on_attach = function(_, bufnr)
--               vim.api.nvim_create_autocmd("BufWritePre", {
--                 buffer = bufnr,
--                 command = "EslintFixAll",
--               })
--             end,
--           }
--         end,
--
--         omnisharp = function()
--           lspconfig.omnisharp.setup {
--             capabilities = capabilities,
--             opts = {
--               -- autoformat = false,
--             },
--             handlers = {
--               ["textDocument/definition"] = require('omnisharp_extended').handler,
--             },
--             cmd = { "dotnet", getInstallPath("omnisharp") .. "/libexec/OmniSharp.dll",
--               "--languageserver" },
--             enable_editorconfig_support = true,
--             -- set to true if working in a huge codebase maybe
--             enable_ms_build_load_projects_on_demand = false,
--             enable_roslyn_analyzers = true,
--             organize_imports_on_format = false,
--             -- doesn't seem to work?
--             enable_import_completion = true,
--             sdk_include_prereleases = true,
--             analyze_open_documents_only = true,
--           }
--         end
--       }
--     })
--   end
-- }
--
return {}
